//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje_ABG_Recete.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BilesenList
    {
        public int BilesenId { get; set; }
        public short UrunId { get; set; }
        public string BilesenAdi { get; set; }
        public Nullable<decimal> BilesenOrani { get; set; }
    
        public virtual UrunList UrunList { get; set; }
    }
}
