//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje_ABG_Recete.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbAgrobestGrupReceteEntities : DbContext
    {
        public DbAgrobestGrupReceteEntities()
            : base("name=DbAgrobestGrupReceteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BilesenList> BilesenList { get; set; }
        public virtual DbSet<tblSarjNo> tblSarjNo { get; set; }
        public virtual DbSet<UrunList> UrunList { get; set; }
    }
}
