//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje_ABG_Recete.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSarjNo
    {
        public short SarjId { get; set; }
        public short UrunId { get; set; }
        public string SarjNo { get; set; }
        public Nullable<System.DateTime> UrtTarihi { get; set; }
        public Nullable<byte> MiadiOmru { get; set; }
    
        public virtual UrunList UrunList { get; set; }
    }
}
